---
title: "Lab 01: Hello R"
author: "Jiahe Chen"
date: "8/19/2020"
output: 
  html_document: 
    toc: yes
    toc_float: yes
    fig_width: 4
    fig_height: 3
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse) 
library(datasauRus)
```

## Exercise 1

There are 1846 rows and 3 columns. The variables included are "dataset", "x" and "y".

## Exercise 2

```{r}
  dino_data <- datasaurus_dozen %>% filter(dataset == "dino")
  ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
    geom_point()
  dino_data %>% summarize(r = cor(x, y))
```

## Exercise 3

```{r}
  star_data <- datasaurus_dozen %>% filter(dataset == "star")
  ggplot(data = star_data, mapping = aes(x = x, y = y)) +
    geom_point()
  star_data %>% summarize(r = cor(x, y))
```

This is similar to the r of dino.

## Exercise 4

```{r}
  circle_data <- datasaurus_dozen %>% filter(dataset == "circle")
  ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
    geom_point()
  circle_data %>% summarize(r = cor(x, y))
```

This is also similar to the r of dino.

## Exercise 5

```{r fig.height=7, fig.width=6, message=FALSE}
  ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset)) +
    geom_point() +
    facet_wrap(~ dataset, ncol = 3) +
    theme(legend.position = "none")
  datasaurus_dozen %>% group_by(dataset) %>% summarize(r = cor(x, y))
```
